//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 桌面特效小工具 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MyApp : global::System.Configuration.ApplicationSettingsBase {
        
        private static MyApp defaultInstance = ((MyApp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MyApp())));
        
        public static MyApp Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BackGround//2.png")]
        public string Path_background {
            get {
                return ((string)(this["Path_background"]));
            }
            set {
                this["Path_background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UiDesign")]
        public string ClockStyle {
            get {
                return ((string)(this["ClockStyle"]));
            }
            set {
                this["ClockStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysAblove {
            get {
                return ((bool)(this["AlwaysAblove"]));
            }
            set {
                this["AlwaysAblove"] = value;
            }
        }
    }
}
